### ISSUE TITLE
POI覆盖范围

### ISSUE THREAD

**Issue by Kuailun** [WanZixin/SinaWeibo-LocationSignIn-spider#1]
目前看到代码中有关POI的获取是每个城市10页，是否有办法进行扩展呢？谢谢！

**Comment by wanzixin** [comment]
目前新浪微博移动端只给提供前十页，也许pc端提供的多一些，我没有尝试过

**Comment by Kuailun** [comment]
收到，谢谢！



Kind Regards,
YuChen Chai




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WZX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 上午7:56
收件人:&nbsp;"WanZixin/SinaWeibo-LocationSignIn-spider"<SinaWeibo-LocationSignIn-spider@noreply.github.com&gt;;
抄送:&nbsp;"YuChen Chai"<593677394@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WanZixin/SinaWeibo-LocationSignIn-spider] POI覆盖范围 (#1)





 
目前新浪微博移动端只给提供前十页，也许pc端提供的多一些，我没有尝试过

**Comment by Erenjager417** [comment]
您好，请问我遇到这样的错误应该怎样处理呢？它说我超时，然后在处理一个异常的时候又发生了另外的异常。error如下：
Traceback (most recent call last):
  File "D:\Program Files\python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Program Files\python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files\python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Program Files\python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Program Files\python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "D:\Program Files\python36\lib\http\client.py", line 964, in send
    self.connect()
  File "D:\Program Files\python36\lib\http\client.py", line 1392, in connect
    super().connect()
  File "D:\Program Files\python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Program Files\python36\lib\socket.py", line 724, in create_connection
    raise err
  File "D:\Program Files\python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "D:\Program Files\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\Program Files\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\Program Files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\Program Files\python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\Program Files\python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Pycharm/weiboqiandao/crawler.py", line 253, in <module>
    main()
  File "E:/Pycharm/weiboqiandao/crawler.py", line 227, in main
    ippool = build_ippool()
  File "E:\Pycharm\weiboqiandao\buildip.py", line 80, in build_ippool
    results = p.get_proxy(page)
  File "E:\Pycharm\weiboqiandao\buildip.py", line 35, in get_proxy
    res = requests.get(url, proxies=proxy_ip, headers={'User-Agent': UserAgent(use_cache_server=False).random})
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\fake.py", line 69, in __init__
    self.load()
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 178, in load
    raise exc
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "D:\Program Files\python36\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
